# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: document_parser.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'document_parser.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64ocument_parser.proto\x12\x08\x64ocparse\"\x07\n\x05\x45mpty\"p\n\x0cParseRequest\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0f\n\x07task_id\x18\x03 \x01(\t\x12\'\n\x07options\x18\x04 \x01(\x0b\x32\x16.docparse.ParseOptions\"g\n\x0cParseOptions\x12\x16\n\x0e\x65xtract_images\x18\x01 \x01(\x08\x12\x16\n\x0e\x65xtract_tables\x18\x02 \x01(\x08\x12\x11\n\tmax_pages\x18\x03 \x01(\x05\x12\x14\n\x0coutput_style\x18\x04 \x01(\t\"\x96\x01\n\nParseChunk\x12\x13\n\x0bpage_number\x18\x01 \x01(\x05\x12\x13\n\x0btotal_pages\x18\x02 \x01(\x05\x12\x10\n\x08markdown\x18\x03 \x01(\t\x12#\n\x06images\x18\x04 \x03(\x0b\x32\x13.docparse.ImageInfo\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x13\n\x0bis_complete\x18\x06 \x01(\x08\"]\n\tImageInfo\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x10\n\x08image_id\x18\x02 \x01(\t\x12\x10\n\x08\x61lt_text\x18\x03 \x01(\t\x12\r\n\x05width\x18\x04 \x01(\x05\x12\x0e\n\x06height\x18\x05 \x01(\x05\" \n\nFormatList\x12\x12\n\nmime_types\x18\x01 \x03(\t2\x87\x01\n\x0e\x44ocumentParser\x12\x37\n\x05Parse\x12\x16.docparse.ParseRequest\x1a\x14.docparse.ParseChunk0\x01\x12<\n\x13GetSupportedFormats\x12\x0f.docparse.Empty\x1a\x14.docparse.FormatListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'document_parser_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=35
  _globals['_EMPTY']._serialized_end=42
  _globals['_PARSEREQUEST']._serialized_start=44
  _globals['_PARSEREQUEST']._serialized_end=156
  _globals['_PARSEOPTIONS']._serialized_start=158
  _globals['_PARSEOPTIONS']._serialized_end=261
  _globals['_PARSECHUNK']._serialized_start=264
  _globals['_PARSECHUNK']._serialized_end=414
  _globals['_IMAGEINFO']._serialized_start=416
  _globals['_IMAGEINFO']._serialized_end=509
  _globals['_FORMATLIST']._serialized_start=511
  _globals['_FORMATLIST']._serialized_end=543
  _globals['_DOCUMENTPARSER']._serialized_start=546
  _globals['_DOCUMENTPARSER']._serialized_end=681
# @@protoc_insertion_point(module_scope)
